export enum EstadoPaciente {
  ESPERANDO_DETERMINACION,
  SIENDO_DETERMINADO,
  ESPERANDO_AUTORIZACION,
  ESPERANDO_ATENCION,
  ESPERANDO_OBRA,
  SIENDO_ATENDIDO1,
  SIENDO_ATENDIDO2,
  ESPERANDO_PAGO,
  PAGANDO,
  INTERRUMPIDO1,
  INTERRUMPIDO2,
  FINALIZADO,
}
